services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: my_tech_exam_db
      DB_USERNAME: jrmaloc
      DB_PASSWORD: root
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: my_tech_exam_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: jrmaloc
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: