services:
  app:
    build:
      context: .
      dockerfile: docker/dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/var/www
    depends_on:
      - db
    working_dir: /var/www
    environment:
      # Optional: if you're passing env directly to container
      DB_HOST: db
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: my_tech_exam_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: jrmaloc
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: